[package]
name = "burn_dragon_core"
description = "burn dragon core model and utilities"
version = "0.4.0"
edition = "2024"
authors = ["mosure <mitchell@mosure.me>"]
license = "MIT OR Apache-2.0"
keywords = [
  "burn",
  "bdh",
  "language-model",
  "machine-learning",
]
categories = [
  "compression",
  "science",
  "science::neuroscience",
]
homepage = "https://github.com/mosure/burn_bdh"
repository = "https://github.com/mosure/burn_bdh"
readme = "../../README.md"
exclude = [
  ".devcontainer",
  ".github",
  "docs",
  "dist",
  "build",
  "assets",
  "credits",
]

[features]
default = []

benchmark = ["burn/autotune", "burn/fusion"]
train = ["burn/dataset", "dep:image"]
cuda = ["burn-cuda"]
viz = []
web = []

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1"
burn_dragon_wgpu = { path = "../burn_dragon_wgpu", version = "0.4.0" }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"], optional = true }


[dependencies.burn]
version = "0.19"
default-features = false
features = [
  # "autotune",
  "fusion",
  "ndarray",
  "std",
  # "vulkan",
  # "webgpu",
  "wgpu",
]

[dependencies.burn-cuda]
version = "0.19"
optional = true
default-features = false
features = [
  "std",
]


[dev-dependencies]
burn-autodiff = "0.19"
burn-ndarray = "0.19"
burn-wgpu = { version = "0.19", default-features = false, features = ["fusion", "std"] }
tempfile = "3"

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]
